extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
plugins:
  - prettier
  - react
  - filenames
  - jsx-a11y
  - simple-import-sort
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    es6: true
    classes: true
    modules: true
env:
  browser: true
  es6: true
  node: true
  jest: true
rules:
  complexity: [0, 4]
  eqeqeq: 2
  import/no-unresolved: 0
  import/prefer-default-export: 0
  react/prop-types: 1
  no-param-reassign: 1
  react/no-array-index-key: 0
  react/jsx-props-no-spreading: 0
  import/no-extraneous-dependencies: 0
  no-unused-expressions: 0
  react/no-unescaped-entities: 0
  no-alert: 1
  no-console: 1

